shards: 24
reference: 'asm.fasta'
long_reads: 'hifi.fq.gz'
short_reads: 'sr.fq.gz'
model: 'hybrid'
phased: 'unphased'
container: 'deepvariant_1.1.0.sif'
DT_container: 'deepvariant_deeptrio-1.1.0.sif'
GL_container: 'glnexus_v1.2.7.sif'
